import type {
  World,
  Objective,
  Quest,
  Ritual,
  SavePoint,
  InboxItem,
  WaitingForItem,
  FocusSession,
  ActivityEvent,
  UserProfile,
  AvatarConfig,
} from "@/types/domain";

const userId = "demo-user-001";
const now = new Date().toISOString();
const daysAgo = (d: number) =>
  new Date(Date.now() - d * 86400000).toISOString();
const daysFromNow = (d: number) =>
  new Date(Date.now() + d * 86400000).toISOString();

export const SEED_USER: UserProfile = {
  id: userId,
  displayName: "Commander",
  timezone: "America/New_York",
  weeklyCapacityMinutes: 660,
  level: 3,
  totalXp: 485,
  coreHealth: 72,
  planningMode: "BALANCED",
  onboardingCompleted: true,
  gameTerminology: true,
  xpEnabled: true,
  reducedMotion: false,
  quietHoursStart: "22:00",
  quietHoursEnd: "07:00",
  reminderDailyCap: 8,
  createdAt: daysAgo(30),
  updatedAt: now,
};

export const SEED_AVATAR: AvatarConfig = {
  id: "avatar-001",
  userId,
  baseBody: "default",
  skinTone: "medium",
  hairStyle: "short",
  hairColor: "#2D1B00",
  outfitPalette: "cyber-blue",
  accessory: "none",
  unlockedCosmetics: ["cyber-blue", "midnight", "ember"],
};

export const SEED_WORLDS: World[] = ([
  {
    id: "world-interview",
    userId,
    name: "Interview Prep",
    purpose: "Receive a software engineering offer at a top-tier company",
    color: "#3B82F6",
    icon: "briefcase",
    status: "PRIMARY",
    weeklyTargetMinutes: 300,
    preferredCadence: "daily",
    demandType: "DEEP_THINKING",
    importance: 5,
    health: 78,
    sortOrder: 0,
    pauseReason: null,
    resumeReviewAt: null,
    resumeCondition: null,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(1),
  },
  {
    id: "world-gym",
    userId,
    name: "Gym & Health",
    purpose: "Maintain consistent physical fitness and energy levels",
    color: "#F97316",
    icon: "dumbbell",
    status: "MAINTENANCE",
    weeklyTargetMinutes: 120,
    preferredCadence: "3x-week",
    demandType: "PHYSICAL",
    importance: 4,
    health: 55,
    sortOrder: 1,
    pauseReason: null,
    resumeReviewAt: null,
    resumeCondition: null,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(6),
  },
  {
    id: "world-sysdesign",
    userId,
    name: "System Design",
    purpose: "Build deep expertise in distributed systems architecture",
    color: "#8B5CF6",
    icon: "cpu",
    status: "SECONDARY",
    weeklyTargetMinutes: 180,
    preferredCadence: "4x-week",
    demandType: "DEEP_THINKING",
    importance: 4,
    health: 82,
    sortOrder: 2,
    pauseReason: null,
    resumeReviewAt: null,
    resumeCondition: null,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(2),
  },
  {
    id: "world-jobsearch",
    userId,
    name: "Job Search",
    purpose: "Apply to 15 targeted positions and manage the pipeline",
    color: "#F59E0B",
    icon: "search",
    status: "SECONDARY",
    weeklyTargetMinutes: 90,
    preferredCadence: "daily",
    demandType: "ADMINISTRATIVE",
    importance: 5,
    health: 65,
    sortOrder: 3,
    pauseReason: null,
    resumeReviewAt: null,
    resumeCondition: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(3),
  },
  {
    id: "world-personal",
    userId,
    name: "Side Project",
    purpose: "Build a portfolio piece demonstrating full-stack capabilities",
    color: "#EC4899",
    icon: "code",
    status: "PAUSED",
    weeklyTargetMinutes: 0,
    preferredCadence: "weekly",
    demandType: "CREATIVE",
    importance: 2,
    health: -1,
    sortOrder: 4,
    pauseReason: "Focusing on interview prep and job search through July",
    resumeReviewAt: daysFromNow(21),
    resumeCondition: "After receiving an offer or completing interview cycle",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(14),
  },
] as Omit<World, "circleId">[]).map((w) => ({ ...w, circleId: "seed" }));

export const SEED_OBJECTIVES: Objective[] = [
  {
    id: "obj-interview-1",
    worldId: "world-interview",
    title: "Pass technical interviews at 3 target companies",
    description:
      "Prepare behavioral answers, system design responses, and coding skills to pass on-site rounds",
    successCriteria: "Receive at least one offer",
    stage: "MIDDLE",
    progressPercent: 45,
    dueAt: daysFromNow(14),
    importance: 5,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(1),
  },
  {
    id: "obj-gym-1",
    worldId: "world-gym",
    title: "Maintain 3 workouts per week",
    description: "Keep a consistent routine even during interview season",
    successCriteria: "Complete at least 3 sessions per week for 4 weeks",
    stage: "MIDDLE",
    progressPercent: 60,
    dueAt: null,
    importance: 3,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(6),
  },
  {
    id: "obj-sysdesign-1",
    worldId: "world-sysdesign",
    title: "Complete distributed systems study guide",
    description:
      "Work through caching, load balancing, database sharding, and message queues",
    successCriteria: "Can whiteboard any of these topics confidently",
    stage: "MIDDLE",
    progressPercent: 55,
    dueAt: daysFromNow(10),
    importance: 4,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
  {
    id: "obj-jobsearch-1",
    worldId: "world-jobsearch",
    title: "Submit 15 targeted applications",
    description:
      "Apply to companies that match skill set, values, and compensation requirements",
    successCriteria: "15 applications submitted with tailored materials",
    stage: "STARTING",
    progressPercent: 25,
    dueAt: daysFromNow(21),
    importance: 5,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(3),
  },
];

export const SEED_QUESTS: Quest[] = [
  {
    id: "quest-1",
    worldId: "world-interview",
    objectiveId: "obj-interview-1",
    campaignId: null,
    title: "Practice two binary tree problems on LeetCode",
    description: "Focus on DFS/BFS traversal patterns",
    nextMove: "Open LeetCode problem 102 (Binary Tree Level Order Traversal)",
    status: "active",
    dueAt: daysFromNow(1),
    estimatedMinutes: 60,
    importance: 5,
    consequence: "Interview tomorrow requires tree problem fluency",
    demandType: "DEEP_THINKING",
    difficulty: 4,
    priorityScore: 85,
    priorityOverride: null,
    rescheduleCount: 0,
    waitingForId: null,
    isCompleted: false,
    completedAt: null,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: "quest-2",
    worldId: "world-interview",
    objectiveId: "obj-interview-1",
    campaignId: null,
    title: "Record mock behavioral answer for leadership question",
    description:
      "Prepare a STAR-format answer about leading a difficult project",
    nextMove: "Write out key bullet points for the leadership story",
    status: "active",
    dueAt: daysFromNow(2),
    estimatedMinutes: 30,
    importance: 4,
    consequence: "Behavioral round is 40% of interview score",
    demandType: "CREATIVE",
    difficulty: 3,
    priorityScore: 72,
    priorityOverride: null,
    rescheduleCount: 1,
    waitingForId: null,
    isCompleted: false,
    completedAt: null,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: "quest-3",
    worldId: "world-sysdesign",
    objectiveId: "obj-sysdesign-1",
    campaignId: null,
    title: "Study cache invalidation strategies",
    description:
      "Write-through, write-behind, and cache-aside patterns with trade-offs",
    nextMove: "Read chapter 6 of the system design primer",
    status: "active",
    dueAt: daysFromNow(5),
    estimatedMinutes: 45,
    importance: 4,
    consequence: "Cache design is a common interview topic",
    demandType: "DEEP_THINKING",
    difficulty: 4,
    priorityScore: 60,
    priorityOverride: null,
    rescheduleCount: 0,
    waitingForId: null,
    isCompleted: false,
    completedAt: null,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(2),
  },
  {
    id: "quest-4",
    worldId: "world-jobsearch",
    objectiveId: "obj-jobsearch-1",
    campaignId: null,
    title: "Update resume experience section with metrics",
    description: "Add quantified impact to last two roles",
    nextMove: "Open resume doc and list three measurable outcomes from last role",
    status: "active",
    dueAt: daysFromNow(3),
    estimatedMinutes: 45,
    importance: 4,
    consequence: "Applications without metrics get filtered out",
    demandType: "ADMINISTRATIVE",
    difficulty: 2,
    priorityScore: 55,
    priorityOverride: null,
    rescheduleCount: 2,
    waitingForId: null,
    isCompleted: false,
    completedAt: null,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(3),
  },
  {
    id: "quest-5",
    worldId: "world-gym",
    objectiveId: "obj-gym-1",
    campaignId: null,
    title: "Complete upper body workout",
    description: "Push/pull split - bench, rows, overhead press, pull-ups",
    nextMove: "Pack gym bag and pre-workout snack",
    status: "active",
    dueAt: null,
    estimatedMinutes: 50,
    importance: 3,
    consequence: "",
    demandType: "PHYSICAL",
    difficulty: 2,
    priorityScore: 35,
    priorityOverride: null,
    rescheduleCount: 0,
    waitingForId: null,
    isCompleted: false,
    completedAt: null,
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: "quest-6",
    worldId: "world-interview",
    objectiveId: "obj-interview-1",
    campaignId: null,
    title: "Review company culture notes for TechCorp",
    description: "Review mission, recent news, and team structure",
    nextMove: "Open TechCorp research doc and highlight key talking points",
    status: "active",
    dueAt: daysFromNow(1),
    estimatedMinutes: 20,
    importance: 3,
    consequence: "Shows preparation in interview",
    demandType: "LOW_ENERGY",
    difficulty: 1,
    priorityScore: 68,
    priorityOverride: null,
    rescheduleCount: 0,
    waitingForId: null,
    isCompleted: false,
    completedAt: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
];

export const SEED_RITUALS: Ritual[] = [
  {
    id: "ritual-1",
    worldId: "world-interview",
    title: "Daily coding problem",
    cadenceRule: "weekdays",
    minimumVersion: "Review one solved problem",
    targetVersion: "Solve one new medium problem",
    stretchVersion: "Solve one medium + one hard problem",
    estimatedMinutes: 45,
    isActive: true,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: "ritual-2",
    worldId: "world-gym",
    title: "Workout session",
    cadenceRule: "3x-week",
    minimumVersion: "10-minute walk",
    targetVersion: "40-minute strength workout",
    stretchVersion: "Workout plus 15-minute mobility",
    estimatedMinutes: 50,
    isActive: true,
    createdAt: daysAgo(28),
    updatedAt: daysAgo(6),
  },
  {
    id: "ritual-3",
    worldId: "world-sysdesign",
    title: "Study session",
    cadenceRule: "4x-week",
    minimumVersion: "Review notes for 15 minutes",
    targetVersion: "45-minute deep study with notes",
    stretchVersion: "Study session plus whiteboard practice",
    estimatedMinutes: 45,
    isActive: true,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
  },
];

export const SEED_SAVE_POINTS: SavePoint[] = [
  {
    id: "sp-1",
    focusSessionId: null,
    worldId: "world-sysdesign",
    questId: "quest-3",
    completedSummary: "Finished write-through and write-behind patterns",
    stoppingPoint:
      "About to start cache-aside pattern, have notes open on consistency models",
    nextAction: "Read cache-aside section and draw comparison diagram",
    blocker: null,
    resources: "System Design Primer Ch.6, personal notes doc",
    intendedResumeAt: daysFromNow(1),
    createdAt: daysAgo(2),
  },
];

export const SEED_INBOX: InboxItem[] = [
  {
    id: "inbox-1",
    userId,
    rawContent:
      "Look into GraphQL for the portfolio project API layer",
    captureType: "text",
    capturedAt: daysAgo(1),
    processedAt: null,
    targetWorldId: null,
  },
  {
    id: "inbox-2",
    userId,
    rawContent: "Ask mentor about negotiation strategies for offers",
    captureType: "text",
    capturedAt: daysAgo(2),
    processedAt: null,
    targetWorldId: null,
  },
];

export const SEED_WAITING_FOR: WaitingForItem[] = [
  {
    id: "wf-1",
    worldId: "world-jobsearch",
    relatedQuestId: null,
    personOrOrganization: "TechCorp Recruiting",
    awaitedItem: "Interview schedule confirmation",
    requestedAt: daysAgo(3),
    expectedAt: daysFromNow(1),
    followUpAt: daysFromNow(2),
    consequence: "Cannot prepare without knowing interview format",
    nextActionAfterResponse:
      "Review specific interview format and prepare accordingly",
    status: "waiting",
    resolvedAt: null,
    createdAt: daysAgo(3),
  },
];

export const SEED_FOCUS_SESSIONS: FocusSession[] = [
  {
    id: "fs-1",
    worldId: "world-interview",
    questId: "quest-1",
    missionBlockId: null,
    startedAt: daysAgo(1),
    endedAt: daysAgo(1),
    plannedMinutes: 45,
    actualMinutes: 42,
    focusQuality: 4,
    interruptionCount: 1,
    notes: "Completed 3 tree problems, struggled with balanced BST validation",
    xpEarned: 8,
    createdAt: daysAgo(1),
  },
];

export const SEED_ACTIVITY: ActivityEvent[] = [
  {
    id: "ae-1",
    userId,
    worldId: "world-interview",
    eventType: "focus_completed",
    payload: { minutes: 42, quest: "Practice binary tree problems" },
    xpEarned: 8,
    occurredAt: daysAgo(1),
  },
  {
    id: "ae-2",
    userId,
    worldId: "world-sysdesign",
    eventType: "save_point_created",
    payload: { topic: "Cache invalidation" },
    xpEarned: 3,
    occurredAt: daysAgo(2),
  },
  {
    id: "ae-3",
    userId,
    worldId: "world-interview",
    eventType: "quest_completed",
    payload: { quest: "Complete graph traversal worksheet" },
    xpEarned: 10,
    occurredAt: daysAgo(3),
  },
  {
    id: "ae-4",
    userId,
    worldId: "world-personal",
    eventType: "world_paused",
    payload: { reason: "Focusing on interviews" },
    xpEarned: 5,
    occurredAt: daysAgo(14),
  },
  {
    id: "ae-5",
    userId,
    worldId: "world-gym",
    eventType: "ritual_completed",
    payload: { ritual: "Workout session", version: "target" },
    xpEarned: 10,
    occurredAt: daysAgo(6),
  },
];
